// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BannerController from "./banner_controller"
application.register("banner", BannerController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import RoomsController from "./rooms_controller"
application.register("rooms", RoomsController)
